#!/bin/bash

alias tmux='tmux -u' # enable unicode support
alias t='tmux'
alias ta='tmux attach -t'
alias tad='tmux attach -d -t'
alias ts='tmux new-session -s'
alias tl='tmux list-sessions'
alias tksv='tmux kill-server'
alias tkss='tmux kill-session -t'
alias p='~/Scripts/tmux/sessionizer'
