#!/usr/bin/env bash
selected=`cat ~/Scripts/tmux/cheat-words | fzf`
if [[ -z $selected ]]; then
    exit 0
fi

read -p "Enter query: " query

query=`echo $query | tr ' ' '+'`
echo \"curl cht.sh/$selected/$query/\" & curl cht.sh/$selected/$query & while [ : ]; do sleep 1; done
