#!/usr/bin/bash

count=$(tmux list-panes | wc -l)

if [ $count == 1 ]; then
  current_path=$(tmux display -p '#{pane_current_path}')


  if [[ $1 == 'right' ]]; then
    tmux split-window -h -c $current_path
  else
    tmux split-window -v -c $current_path
  fi
  exit 0
fi

current_pane_index=$(tmux display -p "#{pane_index}")

if [[ $current_pane_index = 1 ]]; then
  window_dimensions=$(tmux display -p '#{window_width}x#{window_height}')
  pane_dimensions=$(tmux display -p '#{pane_width}x#{pane_height}')

  if [[ $window_dimensions == $pane_dimensions ]]; then
    move=true
  fi

  tmux resize-pane -t 1 -Z

  if [[ $move ]]; then
    tmux select-pane -R
    tmux select-pane -D
  fi
else
  tmux resize-pane -t 1 -Z
fi
