#!/usr/bin/bash

session_name='kabmat'
window_name='kabmat'
default_dir=/tmp

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $default_dir
    tmux new-window -n $window_name -t $session_name -c $default_dir
    tmux send-keys -t $session_name:$window_name "kabmat" ENTER
    tmux kill-window -t $session_name:1
    return 0
fi

if ! tmux has-session -t=$session_name 2> /dev/null; then
    tmux new-session -ds $session_name -c $default_dir 
    tmux new-window -n $window_name -t $session_name -c /tmp
    tmux send-keys -t $session_name:$window_name "kabmat" ENTER
    tmux kill-window -t $session_name:1
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t=$session_name
else
    tmux switch-client -t=$session_name
fi
