#!/usr/bin/bash

window_name=$1

if [ -z "$window_name" ]; then
  echo "Missing target window (usage: tmux-session-switch <target_session>"
  exit 1
fi

if ! tmux select-window -t $window_name 2>/dev/null ; then
  tmux new-window
fi
