#!/usr/bin/bash

default_dir=/tmp
return_session="default"

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

declare -A custom
custom[dbui]="nvim -c DBUI"
custom[kabmat]="kabmat"

function get_custom_keys() {
  for key in "${!custom[@]}"; do
    echo $key
  done
}

function get_custom_value() {
  local val=$1

  for key in "${!custom[@]}"; do
    if [ "$val" == "$key" ]; then
      echo -e ${custom[$key]}
    fi
  done
}

selected_name=$(echo "$(get_custom_keys)" | tr " " "\n" | fzf )

if [[ -z $selected_name ]]; then
    exit 0
fi

selected_cmd=$(get_custom_value $selected_name)
echo $selected_cmd

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $default_dir
    tmux new-window -n $selected_name -t $selected_name -c $default_dir
    tmux send-keys -t $selected_name:$selected_name "$selected_cmd" ENTER
    tmux kill-window -t $selected_name:1
    return 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $default_dir
    tmux new-window -n $selected_name -t $selected_name -c /tmp
    tmux send-keys -t $selected_name:$selected_name "$selected_cmd" ENTER
    tmux kill-window -t $selected_name:1
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t=$selected_name
else
    tmux switch-client -t=$selected_name
fi
