#!/bin/bash

function tmux-autosession() {
  session_name=$1

  if [ -z "$session_name" ]; then
    echo "Missing target session (usage: tmux-autosession <target_session>"
    return 1
  fi

  if [ ! "$TMUX" ]; then
    tmux attach $session_name
    return 0
  fi

  current_session_name=$(tmux display-message -p "#S")
  if [ ! "$current_session_name" = $session_name ]; then
    if ! tmux has-session -t $session_name 2>/dev/null ; then
      tmux new-session -s $session_name -d
      created=true
    fi

    current_window_name=$(tmux display-message -p "#I")
    tmux switch -t $session_name
    tmux move-window -s $current_session_name:$current_window_name -t $session_name

      # Kill extra window created when session was created (TODO: Find better solution)
      # TODO Find better solution
      if [ "$created" = true ]; then
        tmux kill-window -t 1
      fi
  fi
}

